#' ---
#' title: "Linking maps and time series"
#' author: "Abhijit Dasgupta"
#' date: "`r format(Sys.Date(), '%B %d, %Y')`"
#' output_format:
#'   html_document:
#'     toc: true
#'     toc_float: true
#' ---
#'
#+ preamble, include=F
library(pacman)
abhiR:::reload()
p_load(char = 'DT')
knitr::opts_chunk$set(echo=TRUE)
datadir <-  file.path(find_dropbox(), 'Baabi_GarfieldDeviceDataDownload','Mike Wardian')
load(file.path(datadir,'exdata.rda'))

#' # The data
#'
#' Our run data is stored in a tibble, and it is interpolated so that times in minutes
#' match with the times for the Garmin data. The data looks like this:

run_data %>% slice(500:510)

#' We stored the GPS data in a tibble. We did a bit of data munging so that we'd able
#' to link with our breathing data using minutes since start of the run. Note that the
#' data needs to be extracted from the GPS data storage format, which is some variant of
#' XML. I've already done that extraction here.
#'  It looks something like this:
gpx1 <- gpx %>%
  mutate(Minutes = as.numeric(difftime(Time, min(Time), units = 'mins'))) %>%
  filter(Minutes <= 50) %>%
  left_join(run_data)

gpx1 %>% slice(500:510)

#' Note that I'm displaying two different slices of data here.
#'
#' # Map
#' It's relatively easy to get an interactive map using `leaflet`
leaflet::leaflet(gpx1) %>% addTiles() %>%
  addCircleMarkers(~ Longitude, ~ Latitude, radius = 1, color = 'blue')
#'
#' # Time series
#' It's also relatively easy to get a time series graph of
#' heart rate using `d3scatter`
d3scatter::d3scatter(gpx1, ~Minutes, ~ HR, width="100%", height=450)

#' Why am I using `d3scatter` and not `dygraphs` is that, to link the graphs, I'll
#' be using the [`crosstalk`](https://rstudio.github.io/crosstalk/index.html) package,
#' and not all `htmlwidget` packages are Crosstalk-compatible. `leaflet` is, though.
#'
#' # Putting together linked graphs
#' First we need to create a common structure so that both `d3scatter` and `leaflet` can
#' access the data that we will manipulate at the same time. This is provided by
#' `crosstalk::SharedData`
shared_gpx1 <- crosstalk::SharedData$new(gpx1)

#' Now, to position the graphs on a webpage, we'll use `crosstalk::bscols``which leverage
#' the Bootstrap framework.
bscols(
  leaflet(data = shared_gpx1, width="100%", height=450) %>% addTiles() %>%
    addCircleMarkers(~Longitude, ~Latitude, radius=1, color='blue'),
  list(
    d3scatter(shared_gpx1, ~Minutes, ~ HR, width="100%", height=450)
  )
)
#' # Interactivity
#' Interactivity is generated by manipulating the data using a widget, in this case
#' `crosstalk::filter_slider`. This data manipulation then updates each of the linked
#' graphs

crosstalk::bscols(
  leaflet(data = shared_gpx1, width="100%", height=450) %>% addTiles() %>%
    addCircleMarkers(~Longitude, ~Latitude, radius=1, color='blue'),
  list(
    d3scatter(shared_gpx1, ~Minutes, ~ HR, width="100%", height=450)
  )
)
crosstalk::bscols(
  crosstalk::filter_slider("Minutes","Time", shared_gpx1, ~Minutes, width="100%")
)

#' Further reading
#' [Using Crosstalk](https://rstudio.github.io/crosstalk/using.html)
